CREATE TABLE IF NOT EXISTS addresses (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  street VARCHAR(200) NOT NULL,
  zip VARCHAR(20) NOT NULL,
  city VARCHAR(120) NOT NULL,
  country VARCHAR(120) NOT NULL
);
