INSERT INTO addresses (name, street, zip, city, country) VALUES
('Harish Kumar', 'Hauptstraße 12', '77652', 'Offenburg', 'Germany'),
('Anita Patel', 'Kaiserstraße 8', '76133', 'Karlsruhe', 'Germany'),
('Felix Müller', 'Bergweg 5', '89073', 'Ulm', 'Germany'),
('Lena Schneider', 'Am Rathausplatz 3', '79098', 'Freiburg im Breisgau', 'Germany'),
('Carlos Romero', 'Lindenallee 27', '60311', 'Frankfurt am Main', 'Germany'),
('Sofia Rossi', 'Via Roma 14', '20121', 'Milano', 'Italy'),
('Marek Nowak', 'Ulica Słoneczna 9', '00-001', 'Warszawa', 'Poland'),
('Emma Johnson', 'Baker Street 221B', 'NW1 6XE', 'London', 'United Kingdom'),
('Noah Schmidt', 'Kirchstraße 4', '10115', 'Berlin', 'Germany'),
('Ava Wagner', 'Seestraße 10', '13353', 'Berlin', 'Germany'),
('Jonas Becker', 'Münchener Straße 2', '80331', 'München', 'Germany'),
('Mia Weber', 'Domplatz 1', '50667', 'Köln', 'Germany'),
('Lucas Fischer', 'Elbchaussee 99', '22765', 'Hamburg', 'Germany'),
('Isabella Keller', 'Marktstraße 7', '90402', 'Nürnberg', 'Germany'),
('Ethan Braun', 'Goethestraße 16', '04109', 'Leipzig', 'Germany'),
('Olivia Hoffmann', 'Theaterplatz 2', '01067', 'Dresden', 'Germany'),
('Liam Meier', 'Schlossallee 11', '65183', 'Wiesbaden', 'Germany'),
('Charlotte Köhler', 'Neckarstraße 18', '70173', 'Stuttgart', 'Germany'),
('Benjamin Vogel', 'Altstadtgasse 6', '78462', 'Konstanz', 'Germany'),
('Emilia Richter', 'Königsallee 1', '40212', 'Düsseldorf', 'Germany');
